In [97]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [98]:
df=pd.read_csv("/Users/prajwaldnyandeovare/Documents/programs/E-Commerce-Sales & Customer-Analysis/Data/messy_ecommerce_sales_data.csv")
df.head()

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,Blender,Home,3,38,Cash on Delivery,Shipped,114.00
1,101,Customer_101,ORD-35783,7/5/2025,Smartphone,Electronics,2,abd,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.05
3,103,Customer_103,ORD-57811,3/19/2025,Science,Books,5,233.92,PayPal,Processing,1169.60
4,104,Customer_104,ORD-93614,10/20/2025,Biography,Books,1,552.51,Cash on Delivery,Processing,552.51

In [99]:
df.columns

Index(['ID', ' Customer_Name', 'Order_ID', 'Order_Date', 'Product',
       ' Category', 'Quantity', 'Price', 'Payment_Method', 'Status', 'Total'],
      dtype='object')

In [100]:
df.describe()

               ID         Total
count  103.000000     89.000000
mean   149.640777   1232.949101
std     28.704326   2605.471455
min    100.000000 -20000.000000
25%    125.500000    582.130000
50%    149.000000   1138.760000
75%    174.500000   2153.400000
max    199.000000   4722.700000

In [101]:
df.info

<bound method DataFrame.info of       ID  Customer_Name   Order_ID  Order_Date        Product     Category  \
0    100   Customer_100  ORD-41285  11/22/2024        Blender         Home
1    101   Customer_101  ORD-35783    7/5/2025     Smartphone  Electronics
2    102   Customer_102  ORD-84355  12/23/2024  Tennis Racket       Sports
3    103   Customer_103  ORD-57811   3/19/2025        Science        Books
4    104   Customer_104  ORD-93614  10/20/2025      Biography        Books
..   ...            ...        ...         ...            ...          ...
98   198   Customer_198  ORD-14608   7/27/2025         Vacuum          NaN
99   199   Customer_199  ORD-82922   1/22/2025        Blender         Home
100  175   Customer_175  ORD-56651   2/24/2025     Headphones  Electronics
101  142   Customer_142  ORD-69018  10/30/2025          Shoes     Clothing
102  146   Customer_146  ORD-32755    7/9/2025     Basketball   electronic

    Quantity   Price    Payment_Method      Status     Total
0          3      38  Cash on Delivery     Shipped   114.000
1          2     abd            PayPal  Processing       NaN
2          1  389.05            PayPal   Delivered   389.050
3          5  233.92            PayPal  Processing  1169.600
4          1  552.51  Cash on Delivery  Processing   552.510
..       ...     ...               ...         ...       ...
98         2  497.01  Cash on Delivery     Shipped   994.020
99         5  372.28       Credit Card     Shipped  1861.400
100        1  111.36       Credit Card  Processing    77.952
101        5  645.26       Credit Card     Shipped  3226.300
102        2  705.42     Bank Transfer  Processing  1410.840

[103 rows x 11 columns]>

In [102]:
df.shape

(103, 11)

In [103]:
df.isnull().sum()

ID                 0
 Customer_Name     0
Order_ID           0
Order_Date         0
Product            0
 Category          8
Quantity           5
Price              5
Payment_Method     0
Status             0
Total             14
dtype: int64

In [104]:
df.duplicated().sum()

np.int64(1)

In [105]:
df["Payment_Method"].unique()

array(['Cash on Delivery', 'PayPal', 'Bank Transfer', 'Credit Card'],
      dtype=object)

In [106]:
df.dtypes

ID                  int64
 Customer_Name     object
Order_ID           object
Order_Date         object
Product            object
 Category          object
Quantity           object
Price              object
Payment_Method     object
Status             object
Total             float64
dtype: object

In [107]:
df["Quantity"].unique()

array(['3', '2', '1', '5', nan, '4', '-2', '-5', '4a'], dtype=object)

In [108]:
df["Quantity"].value_counts(dropna=False)

Quantity
5      25
2      21
1      20
4      16
3      13
NaN     5
-2      1
-5      1
4a      1
Name: count, dtype: int64

In [109]:
df["Price"].unique()

array(['38', 'abd', '389.05', '233.92', '552.51', '122.06', '978.63',
       '587.68', '600.29', '168.34', 'four hundred', '865.77', '752.13',
       '411.81', '413.13', '796.84', nan, '10000', '247.82', '438.19',
       '300$', '523.01', '556.93', '615.91', '765.69', '836.8', '336.02',
       '898.69', '736.71', '616.63', '266.7', '343.24', '591.53',
       '446.19', '696.71', '-100', '531.06', '681.38', '588.98', '546.04',
       '645.26', '826.77', '849.07', '860.99', '705.42', '596.15',
       '660.98', '896.38', '206.19', '457.16', '233.11', '278.9',
       '789.64', '40.95', '275.1', '933.58', '163.16', '242.52', '209.32',
       '155.76', '235.26', '587.64', '443.13', '569.38', '593.93',
       '141.49', '582.13', '741.63', '688.68', '942.76', '351.89',
       '187.48', '111.36', '530.52', '69.48', '472.14', '868.67',
       '418.38', '266.48', '538.35', '101.19', '730.92', '365.34',
       '882.96', '504.05', '814.68', '920.37', '881.02', '203.63',
       '522.02', '944.54', '817.46', '160.16', '497.01', '372.28'],
      dtype=object)

In [110]:
df["Price"].value_counts(dropna=False)

Price
NaN       5
111.36    2
abd       2
705.42    2
645.26    2
         ..
616.63    1
736.71    1
898.69    1
336.02    1
372.28    1
Name: count, Length: 95, dtype: int64

In [111]:
df[["Quantity", "Price", "Total"]].head(10)

  Quantity   Price    Total
0        3      38   114.00
1        2     abd      NaN
2        1  389.05   389.05
3        5  233.92  1169.60
4        1  552.51   552.51
5        3  122.06   366.18
6      NaN  978.63      NaN
7        5  587.68  2938.40
8        1  600.29   600.29
9        5  168.34   841.70

In [112]:
df["Total"].unique()

array([   114.   ,        nan,    389.05 ,   1169.6  ,    552.51 ,
          366.18 ,   2938.4  ,    600.29 ,    841.7  ,   1731.54 ,
         3008.52 ,    411.81 ,    826.26 ,   1115.576, -20000.   ,
         1239.1  ,   1752.76 ,   2092.04 ,   1113.86 ,   1847.73 ,
         3062.76 ,   3347.2  ,   1680.1  ,   2696.07 ,   2946.84 ,
         3083.15 ,    266.7  ,   1716.2  ,  -2957.65 ,   1784.76 ,
          696.71 ,   -300.   ,    531.06 ,   1362.76 ,   2355.92 ,
         1638.12 ,   2258.41 ,   4133.85 ,   4245.35 ,   1721.98 ,
         1410.84 ,   2384.6  ,    660.98 ,   4481.9  ,    206.19 ,
          640.024,    699.33 ,   1115.6  ,   3948.2  ,     40.95 ,
         1100.4  ,    933.58 ,    489.48 ,   1212.6  ,    837.28 ,
          311.52 ,    705.78 ,    886.26 ,   1138.76 ,    282.98 ,
          582.13 ,   3708.15 ,   2066.04 ,   1885.52 ,   1759.45 ,
          749.92 ,    111.36 ,   2652.6  ,     69.48 ,   1416.42 ,
         2606.01 ,    836.76 ,    266.48 ,   2153.4  ,    404.76 ,
         1023.288,    365.34 ,   2648.88 ,   2520.25 ,    814.68 ,
          920.37 ,   1762.04 ,   4722.7  ,   4087.3  ,    160.16 ,
          994.02 ,   1861.4  ,     77.952,   3226.3  ])

In [113]:
df["Status"].unique()

array(['Shipped', 'Processing', 'Delivered', 'Cancelled', 'Returned'],
      dtype=object)

In [114]:
df["Quantity_clean"] = pd.to_numeric(
    df["Quantity"],
    errors="coerce"
)

In [115]:
df["Quantity_clean"].unique()

array([ 3.,  2.,  1.,  5., nan,  4., -2., -5.])

In [116]:
df["Price_clean"] = pd.to_numeric(
    df["Price"],
    errors="coerce"
)

In [117]:
df["Price_clean"].unique()

array([   38.  ,      nan,   389.05,   233.92,   552.51,   122.06,
         978.63,   587.68,   600.29,   168.34,   865.77,   752.13,
         411.81,   413.13,   796.84, 10000.  ,   247.82,   438.19,
         523.01,   556.93,   615.91,   765.69,   836.8 ,   336.02,
         898.69,   736.71,   616.63,   266.7 ,   343.24,   591.53,
         446.19,   696.71,  -100.  ,   531.06,   681.38,   588.98,
         546.04,   645.26,   826.77,   849.07,   860.99,   705.42,
         596.15,   660.98,   896.38,   206.19,   457.16,   233.11,
         278.9 ,   789.64,    40.95,   275.1 ,   933.58,   163.16,
         242.52,   209.32,   155.76,   235.26,   587.64,   443.13,
         569.38,   593.93,   141.49,   582.13,   741.63,   688.68,
         942.76,   351.89,   187.48,   111.36,   530.52,    69.48,
         472.14,   868.67,   418.38,   266.48,   538.35,   101.19,
         730.92,   365.34,   882.96,   504.05,   814.68,   920.37,
         881.02,   203.63,   522.02,   944.54,   817.46,   160.16,
         497.01,   372.28])

In [118]:
df[["Quantity", "Quantity_clean", "Price", "Price_clean"]]

    Quantity  Quantity_clean   Price  Price_clean
0          3             3.0      38        38.00
1          2             2.0     abd          NaN
2          1             1.0  389.05       389.05
3          5             5.0  233.92       233.92
4          1             1.0  552.51       552.51
..       ...             ...     ...          ...
98         2             2.0  497.01       497.01
99         5             5.0  372.28       372.28
100        1             1.0  111.36       111.36
101        5             5.0  645.26       645.26
102        2             2.0  705.42       705.42

[103 rows x 4 columns]

In [119]:
df["Expected_Total"]=df["Quantity_clean"]*df["Price_clean"]

In [120]:
df["Difference"]=df["Expected_Total"]-df["Total"]

In [121]:
df["Difference"].unique()

array([ 0.00000000e+00,             nan, -4.54747351e-13,  4.78104000e+02,
        4.54747351e-13,  9.67890000e+02,  2.74296000e+02,  2.27373675e-13,
       -2.27373675e-13,  4.38552000e+02,  3.34080000e+01])

In [122]:
df["Difference"].value_counts(dropna=False)

Difference
 0.000000e+00    78
 NaN             14
-4.547474e-13     2
-2.273737e-13     2
 4.781040e+02     1
 4.547474e-13     1
 9.678900e+02     1
 2.742960e+02     1
 2.273737e-13     1
 4.385520e+02     1
 3.340800e+01     1
Name: count, dtype: int64

In [123]:
df["Difference"]=abs(df["Difference"])

In [124]:
df[["Quantity", "Price", "Total" , "Expected_Total" , "Difference" , "Status"]]

    Quantity   Price     Total  Expected_Total    Difference      Status
0          3      38   114.000          114.00  0.000000e+00     Shipped
1          2     abd       NaN             NaN           NaN  Processing
2          1  389.05   389.050          389.05  0.000000e+00   Delivered
3          5  233.92  1169.600         1169.60  0.000000e+00  Processing
4          1  552.51   552.510          552.51  0.000000e+00  Processing
..       ...     ...       ...             ...           ...         ...
98         2  497.01   994.020          994.02  0.000000e+00     Shipped
99         5  372.28  1861.400         1861.40  2.273737e-13     Shipped
100        1  111.36    77.952          111.36  3.340800e+01  Processing
101        5  645.26  3226.300         3226.30  0.000000e+00     Shipped
102        2  705.42  1410.840         1410.84  0.000000e+00  Processing

[103 rows x 6 columns]

In [125]:
df["Difference"].value_counts(dropna=False)

Difference
0.000000e+00    78
NaN             14
4.547474e-13     3
2.273737e-13     3
4.781040e+02     1
9.678900e+02     1
2.742960e+02     1
4.385520e+02     1
3.340800e+01     1
Name: count, dtype: int64

In [126]:
df[df["Difference"] > 0.01][
    [" Category", "Quantity_clean", "Price_clean",
     "Total", "Expected_Total", "Difference", "Status"]
]

,Category,Quantity_clean,Price_clean,Total,Expected_Total,Difference,Status
15,Books,2.0,796.84,1115.576,1593.68,478.104,Returned
42,Clothing,5.0,645.26,2258.410,3226.30,967.890,Shipped
51,Books,2.0,457.16,640.024,914.32,274.296,Processing
85,Sports,2.0,730.92,1023.288,1461.84,438.552,Cancelled
100,Electronics,1.0,111.36,77.952,111.36,33.408,Processing

In [127]:
df["Adjustment_ratio"]=df["Total"]/df["Expected_Total"]

In [128]:
df["Adjustment_ratio"].unique()

array([1. , nan, 1. , 0.7, 1. , 0.7])

In [129]:
df["Adjustment_ratio"].value_counts(dropna=False)

Adjustment_ratio
1.0    78
NaN    14
1.0     5
0.7     4
1.0     1
0.7     1
Name: count, dtype: int64

In [130]:
df["Adjustment_ratio"].round(2).value_counts(dropna=False)

Adjustment_ratio
1.0    84
NaN    14
0.7     5
Name: count, dtype: int64

In [131]:
df["Discount_Rate"]=100-df["Adjustment_ratio"]*100

In [132]:
df["Discount_Rate"].round(2).value_counts(dropna=False)

Discount_Rate
0.0     84
NaN     14
30.0     5
Name: count, dtype: int64

In [133]:
df[df["Quantity_clean"].isnull()][
    [ "Quantity_clean" , "Quantity" , "Price_clean" , "Price" , "Total" ]
]

    Quantity_clean Quantity  Price_clean   Price  Total
6              NaN      NaN       978.63  978.63    NaN
64             NaN      NaN       587.64  587.64    NaN
67             NaN      NaN       593.93  593.93    NaN
92             NaN       4a       203.63  203.63    NaN
93             NaN      NaN       522.02  522.02    NaN
96             NaN      NaN          NaN     abd    NaN

In [134]:
df[df["Price_clean"].isnull()][
    [ "Quantity_clean", "Quantity" , "Price_clean" , "Price" , "Total" ]
]

    Quantity_clean Quantity  Price_clean         Price  Total
1              2.0        2          NaN           abd    NaN
10             5.0        5          NaN  four hundred    NaN
16             4.0        4          NaN           NaN    NaN
20             5.0        5          NaN          300$    NaN
24             5.0        5          NaN           NaN    NaN
30             2.0        2          NaN           NaN    NaN
56             2.0        2          NaN           NaN    NaN
83             5.0        5          NaN           NaN    NaN
96             NaN      NaN          NaN           abd    NaN

In [135]:
df[df["Total"].isnull()][
    [ "Quantity_clean" , "Quantity" , "Price_clean" , "Price" , "Total" ]
]

    Quantity_clean Quantity  Price_clean         Price  Total
1              2.0        2          NaN           abd    NaN
6              NaN      NaN       978.63        978.63    NaN
10             5.0        5          NaN  four hundred    NaN
16             4.0        4          NaN           NaN    NaN
20             5.0        5          NaN          300$    NaN
24             5.0        5          NaN           NaN    NaN
30             2.0        2          NaN           NaN    NaN
56             2.0        2          NaN           NaN    NaN
64             NaN      NaN       587.64        587.64    NaN
67             NaN      NaN       593.93        593.93    NaN
83             5.0        5          NaN           NaN    NaN
92             NaN       4a       203.63        203.63    NaN
93             NaN      NaN       522.02        522.02    NaN
96             NaN      NaN          NaN           abd    NaN

In [136]:
df[df[" Category"].isnull()][
    [ "Order_ID" , "Product" , " Category"]
]

     Order_ID     Product  Category
33  ORD-68182   Biography       NaN
36  ORD-20985  Headphones       NaN
80  ORD-86629      Laptop       NaN
81  ORD-54481  Smartphone       NaN
82  ORD-79672       Shoes       NaN
84  ORD-67799       Jeans       NaN
93  ORD-42475  Basketball       NaN
98  ORD-14608      Vacuum       NaN

In [137]:
product_to_category = (
    df.dropna(subset=[" Category"])
      .drop_duplicates("Product")
      .set_index("Product")[" Category"]
)
df[" Category"] = df[" Category"].fillna(
    df["Product"].map(product_to_category)
)

In [138]:
df["Raw Quantity"]=df["Quantity"].str.extract(r"(-?\d+)")

In [139]:
df = df.drop(columns=["Raw Quantity"])

In [140]:
df["Quantity_clean"].unique()

array([ 3.,  2.,  1.,  5., nan,  4., -2., -5.])

In [141]:
df[df["Quantity"].astype(str).str.contains(r"4a|-", regex=True, na=False)][
    ["Quantity", "Quantity_clean", "Status"]
]

   Quantity  Quantity_clean      Status
17       -2            -2.0  Processing
34       -5            -5.0     Shipped
92       4a             NaN    Returned

In [142]:
df["Price"].unique()

array(['38', 'abd', '389.05', '233.92', '552.51', '122.06', '978.63',
       '587.68', '600.29', '168.34', 'four hundred', '865.77', '752.13',
       '411.81', '413.13', '796.84', nan, '10000', '247.82', '438.19',
       '300$', '523.01', '556.93', '615.91', '765.69', '836.8', '336.02',
       '898.69', '736.71', '616.63', '266.7', '343.24', '591.53',
       '446.19', '696.71', '-100', '531.06', '681.38', '588.98', '546.04',
       '645.26', '826.77', '849.07', '860.99', '705.42', '596.15',
       '660.98', '896.38', '206.19', '457.16', '233.11', '278.9',
       '789.64', '40.95', '275.1', '933.58', '163.16', '242.52', '209.32',
       '155.76', '235.26', '587.64', '443.13', '569.38', '593.93',
       '141.49', '582.13', '741.63', '688.68', '942.76', '351.89',
       '187.48', '111.36', '530.52', '69.48', '472.14', '868.67',
       '418.38', '266.48', '538.35', '101.19', '730.92', '365.34',
       '882.96', '504.05', '814.68', '920.37', '881.02', '203.63',
       '522.02', '944.54', '817.46', '160.16', '497.01', '372.28'],
      dtype=object)

In [143]:
df[df["Total"].isnull()][
    [ "Quantity_clean"  , "Price_clean" , "Total" ]
]

    Quantity_clean  Price_clean  Total
1              2.0          NaN    NaN
6              NaN       978.63    NaN
10             5.0          NaN    NaN
16             4.0          NaN    NaN
20             5.0          NaN    NaN
24             5.0          NaN    NaN
30             2.0          NaN    NaN
56             2.0          NaN    NaN
64             NaN       587.64    NaN
67             NaN       593.93    NaN
83             5.0          NaN    NaN
92             NaN       203.63    NaN
93             NaN       522.02    NaN
96             NaN          NaN    NaN

In [144]:
df["Total"] = df["Total"].fillna(
    df["Quantity_clean"] * df["Price_clean"]
)

In [145]:
df["Raw Price"] = df["Price"].str.replace("four hundred", "400")
df["Raw Price"] = df["Raw Price"].str.extract(r"(-?\d+\.?\d*)")
df["Price_clean"] = pd.to_numeric(
    df["Raw Price"], errors="coerce"
)
df = df.drop(columns=["Raw Price"])

In [146]:
df["Total"] = df["Total"].fillna(
    df["Quantity_clean"] * df["Price_clean"]
)

In [147]:
df[df["Total"].isnull()][
    [ "Quantity_clean"  , "Price_clean" , "Total" ]
]

    Quantity_clean  Price_clean  Total
1              2.0          NaN    NaN
6              NaN       978.63    NaN
16             4.0          NaN    NaN
24             5.0          NaN    NaN
30             2.0          NaN    NaN
56             2.0          NaN    NaN
64             NaN       587.64    NaN
67             NaN       593.93    NaN
83             5.0          NaN    NaN
92             NaN       203.63    NaN
93             NaN       522.02    NaN
96             NaN          NaN    NaN

In [148]:
df[df["Price_clean"] < 0][
    ["Product", "Quantity_clean", "Price_clean", "Total", "Status"]
]

   Product  Quantity_clean  Price_clean  Total     Status
37  Vacuum             3.0       -100.0 -300.0  Delivered

In [149]:
df[df["Price_clean"].isnull()][
    ["Product", "Quantity_clean", "Price_clean", "Total", "Status"]
]

          Product  Quantity_clean  Price_clean  Total      Status
1      Smartphone             2.0          NaN    NaN  Processing
16      Microwave             4.0          NaN    NaN  Processing
24         Comics             5.0          NaN    NaN   Cancelled
30  Tennis Racket             2.0          NaN    NaN  Processing
56          Jeans             2.0          NaN    NaN     Shipped
83          Shoes             5.0          NaN    NaN    Returned
96         Vacuum             NaN          NaN    NaN   Delivered

In [150]:
df.groupby("Product")["Price_clean"].agg(["count", "min", "max", "mean"])

               count     min       max         mean
Product
Basketball         8  400.00    705.42   558.765000
Biography          5  141.49    817.46   488.476000
Blender            8   38.00  10000.00  1603.811250
Comics             6  457.16    942.76   743.046667
Fiction            5  411.81    881.02   644.938000
Football           2  730.92    849.07   789.995000
Headphones         3  111.36    696.71   306.476667
Jacket             3  203.63    596.15   358.293333
Jeans              2  101.19    741.63   421.410000
Lamp               7  233.11    944.54   627.228571
Laptop             4   69.48    860.99   428.547500
Microwave          4  163.16    556.93   352.905000
Science            6  209.32    736.71   378.430000
Shoes              7  443.13    836.80   649.944286
Smartphone         4  266.48    882.96   560.987500
Smartwatch         3  235.26    933.58   538.343333
T-shirt            3  569.38    826.77   662.560000
Tennis Racket      6  122.06    660.98   400.035000
Vacuum             4 -100.00    920.37   483.322500
Yoga Mat           5  206.19    868.67   384.092000
shoes              1   40.95     40.95    40.950000

In [151]:
df["Normalize_Product"]=df["Product"].str.lower()

In [152]:
df.groupby("Normalize_Product")["Product"].nunique()

Normalize_Product
basketball       1
biography        1
blender          1
comics           1
fiction          1
football         1
headphones       1
jacket           1
jeans            1
lamp             1
laptop           1
microwave        1
science          1
shoes            2
smartphone       1
smartwatch       1
t-shirt          1
tennis racket    1
vacuum           1
yoga mat         1
Name: Product, dtype: int64

In [153]:
df["Normalize_Product"]

0            blender
1         smartphone
2      tennis racket
3            science
4          biography
           ...
98            vacuum
99           blender
100       headphones
101            shoes
102       basketball
Name: Normalize_Product, Length: 103, dtype: object

In [154]:
valid=df["Order_ID"].str.match(r"^ORD-\d{5}$")
valid.value_counts()

Order_ID
True    103
Name: count, dtype: int64

In [155]:
df["Order_Date"].head(20)

0     11/22/2024
1       7/5/2025
2     12/23/2024
3      3/19/2025
4     10/20/2025
5     11/20/2024
6       2/2/2025
7       1/3/2025
8     10/23/2025
9       5/3/2025
10     9/26/2025
11    10/22/2025
12      3/2/2025
13     7/24/2025
14    Jan 5 2023
15     1/10/2025
16    10/30/2025
17     2/12/2025
18     5/31/2025
19    12/19/2024
Name: Order_Date, dtype: object

In [156]:
df["Order_Date_clean"] = pd.to_datetime(
    df["Order_Date"],
    errors="coerce"
)

In [157]:
df[["Order_Date", "Order_Date_clean"]].head(20)

    Order_Date Order_Date_clean
0   11/22/2024       2024-11-22
1     7/5/2025       2025-07-05
2   12/23/2024       2024-12-23
3    3/19/2025       2025-03-19
4   10/20/2025       2025-10-20
5   11/20/2024       2024-11-20
6     2/2/2025       2025-02-02
7     1/3/2025       2025-01-03
8   10/23/2025       2025-10-23
9     5/3/2025       2025-05-03
10   9/26/2025       2025-09-26
11  10/22/2025       2025-10-22
12    3/2/2025       2025-03-02
13   7/24/2025       2025-07-24
14  Jan 5 2023              NaT
15   1/10/2025       2025-01-10
16  10/30/2025       2025-10-30
17   2/12/2025       2025-02-12
18   5/31/2025       2025-05-31
19  12/19/2024       2024-12-19

In [158]:
df[df["Order_Date_clean"].isnull()][
    ["Order_Date"]
]

    Order_Date
14  Jan 5 2023
92         abc

In [159]:
df["Price_clean"].unique()

array([   38.  ,      nan,   389.05,   233.92,   552.51,   122.06,
         978.63,   587.68,   600.29,   168.34,   400.  ,   865.77,
         752.13,   411.81,   413.13,   796.84, 10000.  ,   247.82,
         438.19,   300.  ,   523.01,   556.93,   615.91,   765.69,
         836.8 ,   336.02,   898.69,   736.71,   616.63,   266.7 ,
         343.24,   591.53,   446.19,   696.71,  -100.  ,   531.06,
         681.38,   588.98,   546.04,   645.26,   826.77,   849.07,
         860.99,   705.42,   596.15,   660.98,   896.38,   206.19,
         457.16,   233.11,   278.9 ,   789.64,    40.95,   275.1 ,
         933.58,   163.16,   242.52,   209.32,   155.76,   235.26,
         587.64,   443.13,   569.38,   593.93,   141.49,   582.13,
         741.63,   688.68,   942.76,   351.89,   187.48,   111.36,
         530.52,    69.48,   472.14,   868.67,   418.38,   266.48,
         538.35,   101.19,   730.92,   365.34,   882.96,   504.05,
         814.68,   920.37,   881.02,   203.63,   522.02,   944.54,
         817.46,   160.16,   497.01,   372.28])

In [160]:
df.loc[df["Order_Date"] == "Jan 5 2023", "Order_Date_clean"] = pd.to_datetime("Jan 5 2023")

In [161]:
df[df["Order_Date_clean"].isnull()][["Order_Date", "Order_Date_clean"]]

   Order_Date Order_Date_clean
92        abc              NaT

In [162]:
df['Product']=df['Normalize_Product']

In [163]:
df.drop(columns=["Normalize_Product"], inplace=True)

In [164]:
df[" Category"].unique()

array(['Home', 'Electronics', 'Sports', 'Books', 'sports', 'Clothing',
       'electronic', 'ELECTRONICS', 'electronics'], dtype=object)

In [165]:
df["category_new"]=df[" Category"].str.lower()

In [166]:
df["category_new"].unique()

array(['home', 'electronics', 'sports', 'books', 'clothing', 'electronic'],
      dtype=object)

In [167]:
df["category_new"]=df["category_new"].replace("electronic","electronics")
df[" Category"]=df["category_new"]
df.drop(columns=["category_new"],inplace=True)

In [168]:
df[" Category"].unique()

array(['home', 'electronics', 'sports', 'books', 'clothing'], dtype=object)

In [169]:
df["Quantity_clean"].unique()

array([ 3.,  2.,  1.,  5., nan,  4., -2., -5.])

In [170]:
df[df["Quantity_clean"] < 0][
    ["Product", "Quantity_clean", "Price_clean", "Total", "Status"]
]

    Product  Quantity_clean  Price_clean     Total      Status
17  blender            -2.0     10000.00 -20000.00  Processing
34  t-shirt            -5.0       591.53  -2957.65     Shipped

In [171]:
df["Quantity_clean"]=np.where(df["Quantity_clean"]<0,df["Quantity_clean"]*-1,df["Quantity_clean"])

In [172]:
df["Quantity_clean"].unique()

array([ 3.,  2.,  1.,  5., nan,  4.])

In [ ]:
df[["Quantity_clean","Total"]]

     Quantity_clean     Total
0               3.0   114.000
1               2.0       NaN
2               1.0   389.050
3               5.0  1169.600
4               1.0   552.510
..              ...       ...
98              2.0   994.020
99              5.0  1861.400
100             1.0    77.952
101             5.0  3226.300
102             2.0  1410.840

[103 rows x 2 columns]

In [ ]:
df["Expected_Total"] = df["Quantity_clean"] * df["Price_clean"]

In [ ]:
df[df["Expected_Total"].notna() & (abs(df["Expected_Total"] - df["Total"]) > 0.01)][
    ["Product", "Quantity_clean", "Price_clean", "Total", "Expected_Total", "Status"]
]

,Product,Quantity_clean,Price_clean,Total,Expected_Total,Status
15,fiction,2.0,796.84,1115.576,1593.68,Returned
17,blender,2.0,10000.00,-20000.000,20000.00,Processing
34,t-shirt,5.0,591.53,-2957.650,2957.65,Shipped
42,shoes,5.0,645.26,2258.410,3226.30,Shipped
51,comics,2.0,457.16,640.024,914.32,Processing
85,football,2.0,730.92,1023.288,1461.84,Cancelled
100,headphones,1.0,111.36,77.952,111.36,Processing

## notna() means “is NOT missing.”

In [174]:
df["Total"]=np.where(df["Total"]<0,df["Total"]*-1,df["Total"])

In [175]:
df[df["Difference"] > 0.01][
    ["Product", "Expected_Total", "Total", "Adjustment_ratio", "Discount_Rate"]
]

        Product  Expected_Total     Total  Adjustment_ratio  Discount_Rate
15      fiction         1593.68  1115.576               0.7           30.0
42        shoes         3226.30  2258.410               0.7           30.0
51       comics          914.32   640.024               0.7           30.0
85     football         1461.84  1023.288               0.7           30.0
100  headphones          111.36    77.952               0.7           30.0

In [176]:
df["Difference"] = abs(df["Expected_Total"] - df["Total"])

In [177]:
df[df["Difference"] > 0.01][
    ["Product", "Quantity_clean", "Price_clean",
     "Total", "Expected_Total", "Difference",
     "Discount_Rate"]
]

,Product,Quantity_clean,Price_clean,Total,Expected_Total,Difference,Discount_Rate
15,fiction,2.0,796.84,1115.576,1593.68,478.104,3.000000e+01
17,blender,2.0,10000.00,20000.000,-20000.00,40000.000,0.000000e+00
34,t-shirt,5.0,591.53,2957.650,-2957.65,5915.300,-2.842171e-14
37,vacuum,3.0,-100.00,300.000,-300.00,600.000,0.000000e+00
42,shoes,5.0,645.26,2258.410,3226.30,967.890,3.000000e+01
51,comics,2.0,457.16,640.024,914.32,274.296,3.000000e+01
85,football,2.0,730.92,1023.288,1461.84,438.552,3.000000e+01
100,headphones,1.0,111.36,77.952,111.36,33.408,3.000000e+01

In [178]:
df["Expected_Total"] = df["Quantity_clean"] * df["Price_clean"]

In [179]:
df["Difference"] = abs(df["Expected_Total"] - df["Total"])

In [180]:
df[df["Product"] == "vacuum"][
    ["Product", "Quantity_clean", "Price_clean", "Total", "Status"]
]

   Product  Quantity_clean  Price_clean    Total      Status
23  vacuum             3.0       615.91  1847.73   Cancelled
37  vacuum             3.0      -100.00   300.00   Delivered
90  vacuum             1.0       920.37   920.37  Processing
96  vacuum             NaN          NaN      NaN   Delivered
98  vacuum             2.0       497.01   994.02     Shipped

In [181]:
df["Price_clean"] = np.where(
    df["Price_clean"] < 0,
    df["Price_clean"] * -1,
    df["Price_clean"]
)

In [182]:
df["Expected_Total"] = df["Quantity_clean"] * df["Price_clean"]

In [183]:
df["Difference"] = abs(df["Expected_Total"] - df["Total"])

In [184]:
df[df["Difference"] > 0.01][
    ["Product", "Quantity_clean", "Price_clean",
     "Total", "Expected_Total", "Difference",
     "Discount_Rate"]
]

,Product,Quantity_clean,Price_clean,Total,Expected_Total,Difference,Discount_Rate
15,fiction,2.0,796.84,1115.576,1593.68,478.104,30.0
42,shoes,5.0,645.26,2258.410,3226.30,967.890,30.0
51,comics,2.0,457.16,640.024,914.32,274.296,30.0
85,football,2.0,730.92,1023.288,1461.84,438.552,30.0
100,headphones,1.0,111.36,77.952,111.36,33.408,30.0

In [185]:
df["Payment_Method"].unique()

array(['Cash on Delivery', 'PayPal', 'Bank Transfer', 'Credit Card'],
      dtype=object)

In [186]:
df["Payment_Method"].str.strip().unique()

array(['Cash on Delivery', 'PayPal', 'Bank Transfer', 'Credit Card'],
      dtype=object)

In [187]:
df[df["Payment_Method"] != df["Payment_Method"].str.strip()][
    ["Payment_Method"]
]

Empty DataFrame
Columns: [Payment_Method]
Index: []

In [188]:
df["Status"].unique()

array(['Shipped', 'Processing', 'Delivered', 'Cancelled', 'Returned'],
      dtype=object)

In [189]:
df[df["Status"]!=df["Status"].str.strip()][
    ["Status"]
]

Empty DataFrame
Columns: [Status]
Index: []

In [190]:
df[" Customer_Name"].unique()

array(['Customer_100', 'Customer_101', 'Customer_102', 'Customer_103',
       'Customer_104', 'Customer_105', 'Customer_106', 'Customer_107',
       'Customer_108', 'Customer_109', 'Customer_110', 'Customer_111',
       'Customer_112', 'Customer_113', 'Customer_114', 'Customer_115',
       'Customer_116', 'Customer_117', 'Customer_118', 'Customer_119',
       'Customer_120', 'Customer_121', 'Customer_122', 'Customer_123',
       'Customer_124', 'Customer_125', 'Customer_126', 'Customer_127',
       'Customer_128', 'Customer_129', 'Customer_130', 'Customer_131',
       'Customer_132', 'Customer_133', 'Customer_134', 'Customer_135',
       'Customer_136', 'Customer_137', 'Customer_138', 'Customer_139',
       'Customer_140', 'Customer_141', 'Customer_142', 'Customer_143',
       'Customer_144', 'Customer_145', 'Customer_146', 'Customer_147',
       'Customer_148', 'Customer_149', 'Customer_150', 'Customer_151',
       'Customer_152', 'Customer_153', 'Customer_154', 'Customer_155',
       'Customer_156', 'Customer_157', 'Customer_158', 'Customer_159',
       'Customer_160', 'Customer_161', 'Customer_162', 'Customer_163',
       'Customer_164', 'Customer_165', 'Customer_166', 'Customer_167',
       'Customer_168', 'Customer_169', 'Customer_170', 'Customer_171',
       'Customer_172', 'Customer_173', 'Customer_174', 'Customer_175',
       'Customer_176', 'Customer_177', 'Customer_178', 'Customer_179',
       'Customer_180', 'Customer_181', 'Customer_182', 'Customer_183',
       'Customer_184', 'Customer_185', 'Customer_186', 'Customer_187',
       'Customer_188', 'Customer_189', 'Customer_190', 'Customer_191',
       'Customer_192', 'Customer_193', 'Customer_194', 'Customer_195',
       'Customer_196', 'Customer_197', 'Customer_198', 'Customer_199'],
      dtype=object)

In [191]:
valid = df[" Customer_Name"].str.match(r"^Customer_\d{3}$")
valid.value_counts()

 Customer_Name
True    103
Name: count, dtype: int64

In [192]:
df[df.duplicated(keep=False)]

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total,Quantity_clean,Price_clean,Expected_Total,Difference,Adjustment_ratio,Discount_Rate,Order_Date_clean
46,146,Customer_146,ORD-32755,7/9/2025,basketball,electronics,2,705.42,Bank Transfer,Processing,1410.84,2.0,705.42,1410.84,0.0,1.0,0.0,2025-07-09
102,146,Customer_146,ORD-32755,7/9/2025,basketball,electronics,2,705.42,Bank Transfer,Processing,1410.84,2.0,705.42,1410.84,0.0,1.0,0.0,2025-07-09

In [193]:
df.duplicated().sum()

np.int64(1)

In [194]:
df = df.drop_duplicates()

In [195]:
df.duplicated().sum()

np.int64(0)

In [196]:
df.isna().sum()

ID                   0
 Customer_Name       0
Order_ID             0
Order_Date           0
Product              0
 Category            0
Quantity             5
Price                5
Payment_Method       0
Status               0
Total               12
Quantity_clean       6
Price_clean          7
Expected_Total      12
Difference          12
Adjustment_ratio    14
Discount_Rate       14
Order_Date_clean     1
dtype: int64

In [197]:
df[df[["Quantity_clean", "Price_clean", "Total"]].isna().any(axis=1)][
    ["Product", "Quantity_clean", "Price_clean", "Total", "Status"]
]

          Product  Quantity_clean  Price_clean  Total      Status
1      smartphone             2.0          NaN    NaN  Processing
6         blender             NaN       978.63    NaN  Processing
16      microwave             4.0          NaN    NaN  Processing
24         comics             5.0          NaN    NaN   Cancelled
30  tennis racket             2.0          NaN    NaN  Processing
56          jeans             2.0          NaN    NaN     Shipped
64  tennis racket             NaN       587.64    NaN    Returned
67     basketball             NaN       593.93    NaN  Processing
83          shoes             5.0          NaN    NaN    Returned
92         jacket             NaN       203.63    NaN    Returned
93     basketball             NaN       522.02    NaN     Shipped
96         vacuum             NaN          NaN    NaN   Delivered

In [199]:
df[df["Price_clean"].isna()][
    ["Price", "Price_clean"]
]

   Price  Price_clean
1    abd          NaN
16   NaN          NaN
24   NaN          NaN
30   NaN          NaN
56   NaN          NaN
83   NaN          NaN
96   abd          NaN

In [200]:
df[df["Quantity_clean"].isna()][
    ["Quantity", "Quantity_clean"]
]

   Quantity  Quantity_clean
6       NaN             NaN
64      NaN             NaN
67      NaN             NaN
92       4a             NaN
93      NaN             NaN
96      NaN             NaN

In [201]:
extracted = pd.to_numeric(
    df["Quantity"].str.extract(r"(-?\d+)")[0],
    errors="coerce"
)

In [204]:
df = df.copy()

In [205]:
df["Quantity_clean"] = df["Quantity_clean"].fillna(extracted)

In [206]:
df[df["Quantity_clean"].isna()][
    ["Quantity", "Quantity_clean"]
]

   Quantity  Quantity_clean
6       NaN             NaN
64      NaN             NaN
67      NaN             NaN
93      NaN             NaN
96      NaN             NaN

In [207]:
df[df["Price_clean"].isna()][
    ["Price", "Price_clean"]
]

   Price  Price_clean
1    abd          NaN
16   NaN          NaN
24   NaN          NaN
30   NaN          NaN
56   NaN          NaN
83   NaN          NaN
96   abd          NaN

In [ ]:
df[df["Total"].isna()][
    ["Product", "Quantity_clean", "Price_clean", "Total"]
]

          Product  Quantity_clean  Price_clean  Total  Expected_Total
1      smartphone             2.0          NaN    NaN             NaN
6         blender             NaN       978.63    NaN             NaN
16      microwave             4.0          NaN    NaN             NaN
24         comics             5.0          NaN    NaN             NaN
30  tennis racket             2.0          NaN    NaN             NaN
56          jeans             2.0          NaN    NaN             NaN
64  tennis racket             NaN       587.64    NaN             NaN
67     basketball             NaN       593.93    NaN             NaN
83          shoes             5.0          NaN    NaN             NaN
92         jacket             4.0       203.63    NaN             NaN
93     basketball             NaN       522.02    NaN             NaN
96         vacuum             NaN          NaN    NaN             NaN

In [211]:
df["Total"] = df["Total"].fillna(
    df["Quantity_clean"] * df["Price_clean"]
)

In [212]:
df["Expected_Total"] = (
    df["Quantity_clean"] * df["Price_clean"]
)

In [213]:
df.shape

(102, 18)

In [214]:
df.duplicated().sum()

np.int64(0)

In [215]:
df.isna().sum()

ID                   0
 Customer_Name       0
Order_ID             0
Order_Date           0
Product              0
 Category            0
Quantity             5
Price                5
Payment_Method       0
Status               0
Total               11
Quantity_clean       5
Price_clean          7
Expected_Total      11
Difference          12
Adjustment_ratio    14
Discount_Rate       14
Order_Date_clean     1
dtype: int64

In [216]:
df[df["Quantity_clean"] <= 0][
    ["Product", "Quantity_clean"]
]

Empty DataFrame
Columns: [Product, Quantity_clean]
Index: []

In [217]:
df[df["Price_clean"] <= 0][
    ["Product", "Price_clean"]
]

Empty DataFrame
Columns: [Product, Price_clean]
Index: []

In [218]:
check = df[
    df["Quantity_clean"].notna() &
    df["Price_clean"].notna() &
    df["Total"].notna()
].copy()

check["Calculated_Total"] = (
    check["Quantity_clean"] * check["Price_clean"]
)

In [219]:
check["Total_Difference"] = (
    check["Calculated_Total"] - check["Total"]
)

check[check["Total_Difference"].abs() > 0.01][
    ["Product", "Quantity_clean", "Price_clean",
     "Total", "Calculated_Total", "Total_Difference",
     "Discount_Rate"]
]

,Product,Quantity_clean,Price_clean,Total,Calculated_Total,Total_Difference,Discount_Rate
15,fiction,2.0,796.84,1115.576,1593.68,478.104,30.0
42,shoes,5.0,645.26,2258.410,3226.30,967.890,30.0
51,comics,2.0,457.16,640.024,914.32,274.296,30.0
85,football,2.0,730.92,1023.288,1461.84,438.552,30.0
100,headphones,1.0,111.36,77.952,111.36,33.408,30.0

In [220]:
df["Order_ID"].str.match(r"^ORD-\d{5}$").value_counts()

Order_ID
True    102
Name: count, dtype: int64

In [221]:
df["Order_Date_clean"].dtype

dtype('<M8[ns]')

In [222]:
df[df["Order_Date_clean"].isna()][
    ["Order_Date", "Order_Date_clean"]
]

   Order_Date Order_Date_clean
92        abc              NaT

In [223]:
df["Product"].unique()

array(['blender', 'smartphone', 'tennis racket', 'science', 'biography',
       'basketball', 'comics', 'shoes', 'fiction', 'microwave',
       'yoga mat', 'vacuum', 'lamp', 't-shirt', 'smartwatch',
       'headphones', 'football', 'laptop', 'jacket', 'jeans'],
      dtype=object)

In [224]:
df[" Category"].unique()

array(['home', 'electronics', 'sports', 'books', 'clothing'], dtype=object)

In [225]:
df.to_csv("cleaned_sales_data.csv", index=False)

In [228]:
pd.read_csv("/Users/prajwaldnyandeovare/Documents/programs/E-Commerce-Sales & Customer-Analysis/Data/cleaned_sales_data.csv").shape

(102, 18)